### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by jimmy3211** [ztizzlegaming/csgo-win-big#3]
I can't see file .sql to make database, so i can't test this website

**Comment by sanerdk** [comment]
It's new project. i also installed here either

http://sanerdk.org/x/

**Comment by ztizzlegaming** [comment]
Hey, sorry about that, I have just added the file. Just be sure to give credit to this repo on your own sites!

**Comment by sanerdk** [comment]
i didnt edit my site
